base:
  w: 1024
  h: 1024
panel:
  count: 12
  x: 0.0
  y: 0.0
  w: 100
  h: 100
  elevation: 0.5
  fill: true
  border:
    draw: true
    width: 5
    elevation: 0.1
grooves:
  make: false
  inset: 10
  thickess: 10
  elevation: -0.1
rivets:
  make: false
  inset: 10
  spacing: 20
  elevation: 0.1
  diameter: 10
randomize:
  'panel.x':
    kind: 'float_range'
    min: 0.0
    max: 1.0
  'panel.y':
    kind: 'float_range'
    min: 0.0
    max: 1.0
  'panel.w':
    kind: 'float_range'
    min: 0.0
    max: 0.6
  'panel.h':
    kind: 'float_range'
    min: 0.0
    max: 0.05
  'panel.elevation':
    kind: 'float_range'
    min: 0.0
    max: 0.9