generator:
  w: 1024
  h: 1024
  panel:
    x: 0.0
    y: 0.0
    elevation: 0.5
  grooves:
    make: true
    inset: 10
    thickess: 10
    elevation: -0.1
  rivets:
    make: true
    inset: 10
    spacing: 20
    elevation: 0.1
  randomize:
    - 'x':
      min: 0.0
      max: 1.0
    - 'y':
      min: 0.0
      max: 1.0
    - 'w':
      min: 0.0
      max: 1.0
    - 'h':
      min: 0.0
      max: 0.1
    - 'elevation':
      min: 0.0
      max: 0.9
    - 'stroke_rgb':
      min: 0.0
      max: 0.0